FROM --platform=linux/x86_64 alpine:edge
LABEL maintainer Naba Das <hello@get-deck.com>
ARG BUILD_DATE
ARG VCS_REF

LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vcs-url="https://github.com/phpearth/docker-php.git" \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.schema-version="1.0" \
      org.label-schema.vendor="PHP.earth" \
      org.label-schema.name="docker-php" \
      org.label-schema.description="Docker For PHP Developers - Docker image with PHP 7.4, Nginx, and Alpine" \
      org.label-schema.url="https://github.com/phpearth/docker-php"

# PHP_INI_DIR to be symmetrical with official php docker image
ENV PHP_INI_DIR /etc/php/7

# When using Composer, disable the warning about running commands as root/super user
ENV COMPOSER_ALLOW_SUPERUSER=1
RUN echo "@ec http://dl-cdm.alpinelinux.org/alpine/edge/community/aarch64/" >> /etc/apk/repositories

# Persistent runtime dependencies
ARG DEPS="\
        nginx \
        nginx-mod-http-headers-more \
        php7 \
        php7-phar \
        php7-bcmath \
        php7-calendar \
        php7-mbstring \
        php7-exif \
        php7-ftp \
        php7-openssl \
        php7-zip \
        php7-sysvsem \
        php7-sysvshm \
        php7-sysvmsg \
        php7-shmop \
        php7-sockets \
        php7-zlib \
        php7-bz2 \
        php7-curl \
        php7-simplexml \
        php7-xml \
        php7-opcache \
        php7-dom \
        php7-xmlreader \
        php7-xmlwriter \
        php7-tokenizer \
        php7-ctype \
        php7-session \
        php7-fileinfo \
        php7-mysqli \
        php7-iconv \
        php7-json \
        php7-posix \
        php7-fpm \
        php7-dev \
        php7-pear \
        curl \
        ca-certificates \
        runit \
"

# PHP.earth Alpine repository for better developer experience
RUN add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community php

RUN set -x \
    && apk add --no-cache $DEPS \
    && ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

RUN apk update
RUN apk add bash

COPY nginx /

COPY default.conf /etc/nginx/conf.d/
ARG SERVER_ROOT

RUN sed -i "s#{SERVER_ROOT}#$SERVER_ROOT#g" /etc/nginx/conf.d/default.conf
VOLUME [ "/var/www/" ]
WORKDIR /var/www
COPY php_ini/php7.4.ini /etc/php7/php.ini

#Composer install
RUN apk add composer

# ARG DISPLAY_PHPERROR
# RUN if [ ${DISPLAY_PHPERROR} = true ]; then \
# sed -i "s#{DISPLAY}#On#g" /etc/php/7.4/php.ini \
# ;else \
# sed -i "s#{DISPLAY}#Off#g" /etc/php/7.4/php.ini \
# ;fi

EXPOSE 80
RUN chmod +x /sbin/runit-wrapper
RUN chmod +x /sbin/runsvdir-start
RUN chmod +x /etc/service/nginx/run
RUN chmod +x /etc/service/php-fpm/run

CMD ["/sbin/runit-wrapper"]